name: Lint Checks

on:
  push:
  pull_request:

jobs:
  py-lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - uses: sidharthvijayakumar/pylint@main
        with:
          path: "tests"

  py-lint-branch:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - uses: sidharthvijayakumar/pylint@main
        with:
          path: "tests"
          hass-version: "dev"
          use-hass-branch: true
